cp base.js base1.js
cp base.js base2.js
cp base.js base3.js
cp base.js base4.js
cp base.js base5.js
cp base.js base6.js
cp base.js base7.js
cp base.js base8.js
cp base.js base9.js
cp base.js base10.js
